services:
  - type: web
    name: linkedin-post-generator
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: postgres
    plan: free
